<?php

use App\Http\Controllers\Admin\EntryExportController;
use App\Http\Controllers\Admin\PrintTableController;
use App\Http\Controllers\Api\V1\MediaController;
use App\Livewire\Admin\Accounts\Form as AccountForm;
use App\Livewire\Admin\Accounts\Index as AccountIndex;
use App\Livewire\Admin\Categories\Form as CategoryForm;
use App\Livewire\Admin\Categories\Index as CategoryIndex;
use App\Livewire\Admin\ChooseCompany;
use App\Livewire\Admin\Companies\Form as CompanyForm;
use App\Livewire\Admin\Companies\Index as CompanyIndex;
use App\Livewire\Admin\Dashboard;
use App\Livewire\Admin\Entries\Form as EntryForm;
use App\Livewire\Admin\Entries\Index as EntryIndex;
use App\Livewire\Admin\Entries\Settle as EntrySettle;
use App\Livewire\Admin\Entries\Trash as EntryTrash;
use App\Livewire\Admin\Media\Index as MediaIndex;
use App\Livewire\Admin\Parties\Form as PartyForm;
use App\Livewire\Admin\Parties\Index as PartyIndex;
use App\Livewire\Admin\PaymentMethods\Form as PaymentMethodForm;
use App\Livewire\Admin\PaymentMethods\Index as PaymentMethodIndex;
use App\Livewire\Admin\Profile;
use App\Livewire\Admin\Reports\AccountLedger;
use App\Livewire\Admin\Reports\Dues;
use App\Livewire\Admin\Reports\EmployeeCost;
use App\Livewire\Admin\Reports\IncomeStatement;
use App\Livewire\Admin\Reports\Index as ReportIndex;
use App\Livewire\Admin\Reports\PartyStatement;
use App\Livewire\Admin\Reports\TrialBalance;
use App\Livewire\Admin\Roles\Form as RoleForm;
use App\Livewire\Admin\Roles\Index as RoleIndex;
use App\Livewire\Admin\Settings;
use App\Livewire\Admin\Users\Form as UserForm;
use App\Livewire\Admin\Users\Index as UserIndex;
use App\Livewire\Auth\Login;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/media/{media}/download', [MediaController::class, 'download'])->middleware('signed')->name('media.download');
Route::redirect('/', '/admin');
Route::livewire('/admin/login', Login::class)->middleware('guest')->name('login');
Route::post('/admin/logout', function (Request $request) {
    Auth::logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    return redirect()->route('login');
})->middleware('auth')->name('logout');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'active', 'can:admin.access'])->group(function (): void {
    Route::livewire('/', Dashboard::class)->middleware('can:dashboard.view')->name('dashboard');
    Route::livewire('/choose-company', ChooseCompany::class)->name('choose-company');
    Route::livewire('/profile', Profile::class)->name('profile');
    Route::get('/print/{token}', PrintTableController::class)->where('token', '[A-Za-z0-9]{40}')->name('print');
    Route::livewire('/users', UserIndex::class)->middleware('can:users.view')->name('users.index');
    Route::livewire('/users/create', UserForm::class)->middleware('can:users.create')->name('users.create');
    Route::livewire('/users/{user}/edit', UserForm::class)->middleware('can:users.update')->name('users.edit');
    Route::livewire('/companies', CompanyIndex::class)->middleware('can:companies.view')->name('companies.index');
    Route::livewire('/companies/create', CompanyForm::class)->middleware('can:companies.create')->name('companies.create');
    Route::livewire('/companies/{company}/edit', CompanyForm::class)->middleware('can:companies.update')->name('companies.edit');
    Route::livewire('/roles', RoleIndex::class)->middleware('can:roles.view')->name('roles.index');
    Route::livewire('/roles/create', RoleForm::class)->middleware(['can:roles.create', 'can:permissions.manage'])->name('roles.create');
    Route::livewire('/roles/{role}/edit', RoleForm::class)->middleware('can:roles.update')->name('roles.edit');
    Route::livewire('/accounts', AccountIndex::class)->middleware('can:accounts.view')->name('accounts.index');
    Route::livewire('/accounts/create', AccountForm::class)->middleware(['can:accounts.manage', 'company.selected'])->name('accounts.create');
    Route::livewire('/accounts/{account}/edit', AccountForm::class)->middleware('can:accounts.manage')->name('accounts.edit');
    Route::livewire('/entries', EntryIndex::class)->middleware('can:entries.view')->name('entries.index');
    Route::get('/entries/export', EntryExportController::class)->middleware('can:entries.view')->name('entries.export');
    Route::livewire('/entries/trash', EntryTrash::class)->middleware('can:entries.delete')->name('entries.trash');
    Route::livewire('/entries/create/{type}', EntryForm::class)->whereIn('type', ['income', 'expense', 'transfer'])->middleware(['can:entries.create', 'company.selected'])->name('entries.create');
    Route::livewire('/entries/{entry}/edit', EntryForm::class)->middleware('can:entries.update')->name('entries.edit');
    Route::livewire('/entries/{entry}/settle', EntrySettle::class)->middleware('can:entries.create')->name('entries.settle');
    Route::livewire('/entries/{entry}/settlement/edit', EntrySettle::class)->middleware('can:entries.update')->name('entries.settlement.edit');
    Route::middleware('can:reports.view')->group(function (): void {
        Route::livewire('/reports', ReportIndex::class)->name('reports.index');
        Route::livewire('/reports/income-statement', IncomeStatement::class)->name('reports.income-statement');
        Route::livewire('/reports/account-ledger', AccountLedger::class)->name('reports.account-ledger');
        Route::livewire('/reports/trial-balance', TrialBalance::class)->name('reports.trial-balance');
        Route::livewire('/reports/employee-cost', EmployeeCost::class)->middleware('can:users.view')->name('reports.employee-cost');
        Route::livewire('/reports/dues', Dues::class)->name('reports.dues');
        Route::livewire('/reports/party-statement', PartyStatement::class)->middleware('can:parties.view')->name('reports.party-statement');
    });
    Route::livewire('/parties', PartyIndex::class)->middleware('can:parties.view')->name('parties.index');
    Route::livewire('/parties/create', PartyForm::class)->middleware(['can:parties.create', 'company.selected'])->name('parties.create');
    Route::livewire('/parties/{party}/edit', PartyForm::class)->middleware('can:parties.update')->name('parties.edit');
    Route::livewire('/categories', CategoryIndex::class)->middleware('can:accounts.view')->name('categories.index');
    Route::livewire('/categories/create', CategoryForm::class)->middleware('can:accounts.manage')->name('categories.create');
    Route::livewire('/categories/{category}/edit', CategoryForm::class)->middleware('can:accounts.manage')->name('categories.edit');
    Route::livewire('/payment-methods', PaymentMethodIndex::class)->middleware('can:accounts.view')->name('payment-methods.index');
    Route::livewire('/payment-methods/create', PaymentMethodForm::class)->middleware(['can:accounts.manage', 'company.selected'])->name('payment-methods.create');
    Route::livewire('/payment-methods/{paymentMethod}/edit', PaymentMethodForm::class)->middleware('can:accounts.manage')->name('payment-methods.edit');
    Route::livewire('/settings', Settings::class)->middleware('can:settings.view')->name('settings');
    Route::livewire('/media', MediaIndex::class)->middleware('can:media.view')->name('media');
});
