<?php

use App\Enums\DocumentType;
use App\Http\Controllers\Admin\EntryExportController;
use App\Http\Controllers\Admin\LeadImportTemplateController;
use App\Http\Controllers\Admin\PrintTableController;
use App\Http\Controllers\Admin\Sales\DocumentPdfController;
use App\Http\Controllers\Admin\Sales\DocumentPrintController;
use App\Http\Controllers\Admin\Sales\ReceiptController;
use App\Http\Controllers\Admin\Sales\TemplatePreviewController;
use App\Http\Controllers\Api\V1\MediaController;
use App\Http\Controllers\SharedDocumentController;
use App\Livewire\Admin\Accounts\Form as AccountForm;
use App\Livewire\Admin\Accounts\Index as AccountIndex;
use App\Livewire\Admin\Categories\Form as CategoryForm;
use App\Livewire\Admin\Categories\Index as CategoryIndex;
use App\Livewire\Admin\ChooseCompany;
use App\Livewire\Admin\Companies\Form as CompanyForm;
use App\Livewire\Admin\Companies\Index as CompanyIndex;
use App\Livewire\Admin\Crm\Calls\Form as CallForm;
use App\Livewire\Admin\Crm\Calls\Index as CallIndex;
use App\Livewire\Admin\Crm\Dashboard as CrmDashboard;
use App\Livewire\Admin\Crm\Emails\Form as EmailForm;
use App\Livewire\Admin\Crm\Emails\Index as EmailIndex;
use App\Livewire\Admin\Crm\Insights as CrmInsights;
use App\Livewire\Admin\Crm\Leads\Form as LeadForm;
use App\Livewire\Admin\Crm\Leads\Index as LeadIndex;
use App\Livewire\Admin\Crm\Leads\Show as LeadShow;
use App\Livewire\Admin\Crm\Reports\Calls as CrmCallReport;
use App\Livewire\Admin\Crm\Reports\Index as CrmReportIndex;
use App\Livewire\Admin\Crm\Reports\Performance as CrmPerformance;
use App\Livewire\Admin\Crm\Reports\Pipeline as CrmPipeline;
use App\Livewire\Admin\Crm\Reports\Sources as CrmSources;
use App\Livewire\Admin\Crm\Services\Form as CrmServiceForm;
use App\Livewire\Admin\Crm\Services\Index as CrmServiceIndex;
use App\Livewire\Admin\Crm\Sources\Form as CrmSourceForm;
use App\Livewire\Admin\Crm\Sources\Index as CrmSourceIndex;
use App\Livewire\Admin\Crm\Statuses\Form as CrmStatusForm;
use App\Livewire\Admin\Crm\Statuses\Index as CrmStatusIndex;
use App\Livewire\Admin\Dashboard;
use App\Livewire\Admin\Entries\Form as EntryForm;
use App\Livewire\Admin\Entries\Index as EntryIndex;
use App\Livewire\Admin\Entries\Settle as EntrySettle;
use App\Livewire\Admin\Entries\Trash as EntryTrash;
use App\Livewire\Admin\Media\Index as MediaIndex;
use App\Livewire\Admin\Parties\Form as PartyForm;
use App\Livewire\Admin\Parties\Index as PartyIndex;
use App\Livewire\Admin\PartyCategories\Form as PartyCategoryForm;
use App\Livewire\Admin\PartyCategories\Index as PartyCategoryIndex;
use App\Livewire\Admin\PaymentMethods\Form as PaymentMethodForm;
use App\Livewire\Admin\PaymentMethods\Index as PaymentMethodIndex;
use App\Livewire\Admin\Profile;
use App\Livewire\Admin\Reports\AccountLedger;
use App\Livewire\Admin\Reports\Dues;
use App\Livewire\Admin\Reports\EmployeeCost;
use App\Livewire\Admin\Reports\IncomeStatement;
use App\Livewire\Admin\Reports\Index as ReportIndex;
use App\Livewire\Admin\Reports\PartyStatement;
use App\Livewire\Admin\Reports\TrialBalance;
use App\Livewire\Admin\Roles\Form as RoleForm;
use App\Livewire\Admin\Roles\Index as RoleIndex;
use App\Livewire\Admin\Sales\Dashboard as SalesDashboard;
use App\Livewire\Admin\Sales\Documents\Form as DocumentForm;
use App\Livewire\Admin\Sales\Documents\Index as DocumentIndex;
use App\Livewire\Admin\Sales\Documents\Show as DocumentShow;
use App\Livewire\Admin\Sales\ItemCategories\Form as ItemCategoryForm;
use App\Livewire\Admin\Sales\ItemCategories\Index as ItemCategoryIndex;
use App\Livewire\Admin\Sales\Items\Form as ItemForm;
use App\Livewire\Admin\Sales\Items\Index as ItemIndex;
use App\Livewire\Admin\Sales\Recurring\Form as RecurringForm;
use App\Livewire\Admin\Sales\Recurring\Index as RecurringIndex;
use App\Livewire\Admin\Sales\Reports\Ageing as SalesAgeing;
use App\Livewire\Admin\Sales\Reports\Breakdown as SalesBreakdown;
use App\Livewire\Admin\Sales\Reports\Index as SalesReportIndex;
use App\Livewire\Admin\Sales\Reports\Register as SalesRegister;
use App\Livewire\Admin\Sales\Reports\Vat as SalesVat;
use App\Livewire\Admin\Sales\Settings as SalesSettings;
use App\Livewire\Admin\Sales\Templates\Form as TemplateForm;
use App\Livewire\Admin\Sales\Templates\Index as TemplateIndex;
use App\Livewire\Admin\Settings;
use App\Livewire\Admin\Users\Form as UserForm;
use App\Livewire\Admin\Users\Index as UserIndex;
use App\Livewire\Auth\Login;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/media/{media}/download', [MediaController::class, 'download'])->middleware('signed')->name('media.download');
Route::redirect('/', '/admin');
Route::livewire('/admin/login', Login::class)->middleware('guest')->name('login');
Route::post('/admin/logout', function (Request $request) {
    Auth::logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    return redirect()->route('login');
})->middleware('auth')->name('logout');

// Public, token-only document links (sales.send creates and revokes them).
Route::middleware('throttle:60,1')->group(function (): void {
    Route::get('/d/{token}', [SharedDocumentController::class, 'show'])->where('token', '[A-Za-z0-9]{40}')->name('documents.shared');
    Route::get('/d/{token}/pdf', [SharedDocumentController::class, 'pdf'])->where('token', '[A-Za-z0-9]{40}')->name('documents.shared.pdf');
});
Route::prefix('admin')->name('admin.')->middleware(['auth', 'active', 'can:admin.access', 'module'])->group(function (): void {
    Route::livewire('/', Dashboard::class)->middleware(['module.home', 'can:dashboard.view'])->name('dashboard');
    Route::livewire('/choose-company', ChooseCompany::class)->name('choose-company');
    Route::livewire('/profile', Profile::class)->name('profile');
    Route::get('/print/{token}', PrintTableController::class)->where('token', '[A-Za-z0-9]{40}')->name('print');
    Route::livewire('/users', UserIndex::class)->middleware('can:users.view')->name('users.index');
    Route::livewire('/users/create', UserForm::class)->middleware('can:users.create')->name('users.create');
    Route::livewire('/users/{user}/edit', UserForm::class)->middleware('can:users.update')->name('users.edit');
    Route::livewire('/companies', CompanyIndex::class)->middleware('can:companies.view')->name('companies.index');
    Route::livewire('/companies/create', CompanyForm::class)->middleware('can:companies.create')->name('companies.create');
    Route::livewire('/companies/{company}/edit', CompanyForm::class)->middleware('can:companies.update')->name('companies.edit');
    Route::livewire('/roles', RoleIndex::class)->middleware('can:roles.view')->name('roles.index');
    Route::livewire('/roles/create', RoleForm::class)->middleware(['can:roles.create', 'can:permissions.manage'])->name('roles.create');
    Route::livewire('/roles/{role}/edit', RoleForm::class)->middleware('can:roles.update')->name('roles.edit');
    Route::livewire('/accounts', AccountIndex::class)->middleware('can:accounts.view')->name('accounts.index');
    Route::livewire('/accounts/create', AccountForm::class)->middleware(['can:accounts.manage', 'company.selected'])->name('accounts.create');
    Route::livewire('/accounts/{account}/edit', AccountForm::class)->middleware('can:accounts.manage')->name('accounts.edit');
    Route::livewire('/entries', EntryIndex::class)->middleware('can:entries.view')->name('entries.index');
    Route::get('/entries/export', EntryExportController::class)->middleware('can:entries.view')->name('entries.export');
    Route::livewire('/entries/trash', EntryTrash::class)->middleware('can:entries.delete')->name('entries.trash');
    Route::livewire('/entries/create/{type}', EntryForm::class)->whereIn('type', ['income', 'expense', 'transfer'])->middleware(['can:entries.create', 'company.selected'])->name('entries.create');
    Route::livewire('/entries/{entry}/edit', EntryForm::class)->middleware('can:entries.update')->name('entries.edit');
    Route::livewire('/entries/{entry}/settle', EntrySettle::class)->middleware('can:entries.create')->name('entries.settle');
    Route::livewire('/entries/{entry}/settlement/edit', EntrySettle::class)->middleware('can:entries.update')->name('entries.settlement.edit');
    Route::middleware('can:reports.view')->group(function (): void {
        Route::livewire('/reports', ReportIndex::class)->name('reports.index');
        Route::livewire('/reports/income-statement', IncomeStatement::class)->name('reports.income-statement');
        Route::livewire('/reports/account-ledger', AccountLedger::class)->name('reports.account-ledger');
        Route::livewire('/reports/trial-balance', TrialBalance::class)->name('reports.trial-balance');
        Route::livewire('/reports/employee-cost', EmployeeCost::class)->middleware('can:users.view')->name('reports.employee-cost');
        Route::livewire('/reports/dues', Dues::class)->name('reports.dues');
        Route::livewire('/reports/party-statement', PartyStatement::class)->middleware('can:parties.view')->name('reports.party-statement');
    });
    Route::livewire('/parties', PartyIndex::class)->middleware('can:parties.view')->name('parties.index');
    Route::livewire('/parties/create', PartyForm::class)->middleware(['can:parties.create', 'company.selected'])->name('parties.create');
    Route::livewire('/parties/{party}/edit', PartyForm::class)->middleware('can:parties.update')->name('parties.edit');
    Route::livewire('/party-categories', PartyCategoryIndex::class)->middleware('can:parties.view')->name('party-categories.index');
    Route::livewire('/party-categories/create', PartyCategoryForm::class)->middleware(['can:parties.update', 'company.selected'])->name('party-categories.create');
    Route::livewire('/party-categories/{partyCategory}/edit', PartyCategoryForm::class)->middleware('can:parties.update')->name('party-categories.edit');
    Route::livewire('/categories', CategoryIndex::class)->middleware('can:accounts.view')->name('categories.index');
    Route::livewire('/categories/create', CategoryForm::class)->middleware('can:accounts.manage')->name('categories.create');
    Route::livewire('/categories/{category}/edit', CategoryForm::class)->middleware('can:accounts.manage')->name('categories.edit');
    Route::livewire('/payment-methods', PaymentMethodIndex::class)->middleware('can:accounts.view')->name('payment-methods.index');
    Route::livewire('/payment-methods/create', PaymentMethodForm::class)->middleware(['can:accounts.manage', 'company.selected'])->name('payment-methods.create');
    Route::livewire('/payment-methods/{paymentMethod}/edit', PaymentMethodForm::class)->middleware('can:accounts.manage')->name('payment-methods.edit');
    Route::livewire('/settings', Settings::class)->middleware('can:settings.view')->name('settings');
    Route::livewire('/media', MediaIndex::class)->middleware('can:media.view')->name('media');
    Route::prefix('crm')->name('crm.')->middleware('can:crm.view')->group(function (): void {
        Route::livewire('/', CrmDashboard::class)->name('dashboard');
        Route::livewire('/insights', CrmInsights::class)->name('insights');
        Route::livewire('/leads', LeadIndex::class)->name('leads.index');
        Route::livewire('/leads/create', LeadForm::class)->middleware(['can:crm.leads.create', 'company.selected'])->name('leads.create');
        Route::get('/leads/import-template', LeadImportTemplateController::class)->middleware('can:crm.leads.import')->name('leads.import-template');
        Route::livewire('/leads/{lead}', LeadShow::class)->whereNumber('lead')->name('leads.show');
        Route::livewire('/leads/{lead}/edit', LeadForm::class)->whereNumber('lead')->middleware('can:crm.leads.update')->name('leads.edit');
        Route::livewire('/leads/{lead}/calls/create', CallForm::class)->whereNumber('lead')->middleware('can:crm.calls.create')->name('calls.create');
        Route::livewire('/calls', CallIndex::class)->name('calls.index');
        Route::livewire('/calls/{call}/edit', CallForm::class)->whereNumber('call')->middleware('can:crm.calls.update')->name('calls.edit');
        Route::livewire('/leads/{lead}/emails/create', EmailForm::class)->whereNumber('lead')->middleware('can:crm.emails.send')->name('emails.create');
        Route::livewire('/emails', EmailIndex::class)->name('emails.index');
        Route::livewire('/services', CrmServiceIndex::class)->name('services.index');
        Route::livewire('/services/create', CrmServiceForm::class)->middleware(['can:crm.setup.manage', 'company.selected'])->name('services.create');
        Route::livewire('/services/{service}/edit', CrmServiceForm::class)->middleware('can:crm.setup.manage')->name('services.edit');
        Route::livewire('/sources', CrmSourceIndex::class)->name('sources.index');
        Route::livewire('/sources/create', CrmSourceForm::class)->middleware(['can:crm.setup.manage', 'company.selected'])->name('sources.create');
        Route::livewire('/sources/{source}/edit', CrmSourceForm::class)->middleware('can:crm.setup.manage')->name('sources.edit');
        Route::livewire('/statuses', CrmStatusIndex::class)->name('statuses.index');
        Route::livewire('/statuses/create', CrmStatusForm::class)->middleware(['can:crm.setup.manage', 'company.selected'])->name('statuses.create');
        Route::livewire('/statuses/{status}/edit', CrmStatusForm::class)->middleware('can:crm.setup.manage')->name('statuses.edit');
        Route::middleware('can:crm.reports.view')->group(function (): void {
            Route::livewire('/reports', CrmReportIndex::class)->name('reports.index');
            Route::livewire('/reports/pipeline', CrmPipeline::class)->name('reports.pipeline');
            Route::livewire('/reports/sources', CrmSources::class)->name('reports.sources');
            Route::livewire('/reports/calls', CrmCallReport::class)->name('reports.calls');
            Route::livewire('/reports/performance', CrmPerformance::class)->name('reports.performance');
        });
    });
    Route::prefix('sales')->name('sales.')->middleware('can:sales.view')->group(function (): void {
        Route::livewire('/', SalesDashboard::class)->name('dashboard');
        foreach (DocumentType::cases() as $documentType) {
            Route::livewire('/'.$documentType->slug(), DocumentIndex::class)->defaults('type', $documentType->value)->name($documentType->slug().'.index');
            Route::livewire('/'.$documentType->slug().'/create', DocumentForm::class)->defaults('type', $documentType->value)
                ->middleware(['can:sales.create', 'company.selected'])->name($documentType->slug().'.create');
        }
        Route::livewire('/documents/{document}', DocumentShow::class)->whereNumber('document')->name('documents.show');
        Route::livewire('/documents/{document}/edit', DocumentForm::class)->whereNumber('document')->middleware('can:sales.update')->name('documents.edit');
        Route::get('/documents/{document}/print', DocumentPrintController::class)->whereNumber('document')->name('documents.print');
        Route::get('/documents/{document}/pdf', DocumentPdfController::class)->whereNumber('document')->name('documents.pdf');
        Route::get('/documents/{document}/receipts/{kind}/{id}', ReceiptController::class)->whereNumber(['document', 'id'])
            ->whereIn('kind', ['payment', 'entry'])->name('documents.receipt');
        Route::livewire('/items', ItemIndex::class)->name('items.index');
        Route::livewire('/items/create', ItemForm::class)->middleware(['can:sales.setup', 'company.selected'])->name('items.create');
        Route::livewire('/items/{item}/edit', ItemForm::class)->middleware('can:sales.setup')->name('items.edit');
        Route::livewire('/item-categories', ItemCategoryIndex::class)->name('item-categories.index');
        Route::livewire('/item-categories/create', ItemCategoryForm::class)->middleware(['can:sales.setup', 'company.selected'])->name('item-categories.create');
        Route::livewire('/item-categories/{itemCategory}/edit', ItemCategoryForm::class)->middleware('can:sales.setup')->name('item-categories.edit');
        Route::livewire('/recurring', RecurringIndex::class)->name('recurring.index');
        Route::livewire('/recurring/create', RecurringForm::class)->middleware(['can:sales.update', 'company.selected'])->name('recurring.create');
        Route::livewire('/recurring/{recurring}/edit', RecurringForm::class)->middleware('can:sales.update')->name('recurring.edit');
        Route::middleware('can:sales.setup')->group(function (): void {
            Route::livewire('/templates', TemplateIndex::class)->name('templates.index');
            Route::livewire('/templates/create', TemplateForm::class)->middleware('company.selected')->name('templates.create');
            Route::livewire('/templates/{template}/edit', TemplateForm::class)->name('templates.edit');
            Route::get('/templates/{template}/preview', TemplatePreviewController::class)->name('templates.preview');
            Route::livewire('/settings', SalesSettings::class)->name('settings');
        });
        Route::middleware('can:sales.reports')->group(function (): void {
            Route::livewire('/reports', SalesReportIndex::class)->name('reports.index');
            Route::livewire('/reports/register', SalesRegister::class)->name('reports.register');
            Route::livewire('/reports/ageing', SalesAgeing::class)->name('reports.ageing');
            Route::livewire('/reports/vat', SalesVat::class)->name('reports.vat');
            Route::livewire('/reports/breakdown', SalesBreakdown::class)->name('reports.breakdown');
        });
    });
});
