<?php

namespace App\Livewire\Admin\Sales\Documents;

use App\Enums\DocumentStatus;
use App\Enums\DocumentType;
use App\Enums\DueStatus;
use App\Models\Document;
use App\Models\Party;
use App\Models\RecurringInvoice;
use App\Support\CompanyContext;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Livewire\Attributes\Locked;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithPagination;

/** The list of one document type (invoices, quotations, bills…) in the header company scope. */
class Index extends Component
{
    use WithPagination;

    private const FILTERS = ['search', 'status', 'from', 'to', 'party', 'recurring'];

    /** Prefix of the status filter values that are payment statuses (invoices and bills). */
    private const DUE_PREFIX = 'due:';

    #[Locked]
    public string $type = '';

    #[Url(except: '')]
    public string $search = '';

    #[Url(except: '')]
    public string $status = '';

    #[Url(except: '')]
    public string $from = '';

    #[Url(except: '')]
    public string $to = '';

    #[Url(except: '')]
    public string $party = '';

    /** Invoices generated by one recurring schedule (linked from the Recurring invoices list). */
    #[Url(except: '')]
    public string $recurring = '';

    public function mount(string $type): void
    {
        Gate::authorize('sales.view');
        abort_unless(DocumentType::tryFrom($type) !== null, 404);
        $this->type = $type;
    }

    public function updated(string $property): void
    {
        if (in_array($property, self::FILTERS, true)) {
            $this->resetPage();
        }
    }

    public function clearFilters(): void
    {
        $this->reset(self::FILTERS);
        $this->resetPage();
    }

    public function render(): View
    {
        Gate::authorize('sales.view');
        $type = DocumentType::from($this->type);
        $context = app(CompanyContext::class);
        $query = $this->filtered($type);
        $issued = (clone $query)->whereNotIn('documents.status', [DocumentStatus::Draft, DocumentStatus::Void]);
        $totals = [
            'count' => (clone $issued)->count(),
            'total' => (int) (clone $issued)->sum('documents.total'),
            // Outstanding of the filtered open documents; the balance expression is portable SQL, summed in an outer query.
            'balance' => $type->isPayable()
                ? (int) DB::query()->fromSub((clone $issued)->withBalance(), 'filtered')->where('balance', '>', 0)->sum('balance')
                : null,
        ];
        $statuses = ['' => __('Any status')] + collect(DocumentStatus::cases())
            ->filter(fn (DocumentStatus $status): bool => $this->offersStatus($type, $status))
            ->mapWithKeys(fn (DocumentStatus $status): array => [$status->value => $status->label()])->all();
        if ($type->isPayable()) {
            $statuses += collect(DueStatus::cases())->mapWithKeys(fn (DueStatus $status): array => [self::DUE_PREFIX.$status->value => $status->label()])->all();
        }

        return view('livewire.admin.sales.documents.index', [
            'documentType' => $type,
            'documents' => (clone $query)->withBalance()->with(['party:id,name', 'company:id,name,code'])
                ->orderByDesc('documents.issue_date')->orderByDesc('documents.id')->paginate(25),
            'totals' => $totals,
            'statuses' => $statuses,
            'parties' => ['' => __('All parties')] + Party::query()->whereIn('company_id', $context->companyIds())->orderBy('name')
                ->get(['id', 'name', 'company_id'])->mapWithKeys(fn (Party $party): array => [$party->id => $party->name])->all(),
            'showCompany' => $context->isAll(),
            'schedule' => ctype_digit($this->recurring) ? RecurringInvoice::query()->whereIn('company_id', app(CompanyContext::class)->companyIds())
                ->whereKey((int) $this->recurring)->value('name') : null,
            'active' => collect([$this->status, $this->party, $this->recurring])->filter(fn (string $value): bool => $value !== '')->count(),
        ])->layout('layouts.admin');
    }

    /** Lifecycle statuses a type can be in: only offers are accepted or declined, only offers and orders converted. */
    private function offersStatus(DocumentType $type, DocumentStatus $status): bool
    {
        return match ($status) {
            DocumentStatus::Accepted, DocumentStatus::Declined => $type->isOffer(),
            DocumentStatus::Converted => $type->convertsTo() !== null,
            default => true,
        };
    }

    /** @return Builder<Document> documents of the type in the header companies the user can see, with the filters */
    private function filtered(DocumentType $type): Builder
    {
        $search = trim(mb_substr($this->search, 0, 100));
        $status = DocumentStatus::tryFrom($this->status);
        $dueStatus = str_starts_with($this->status, self::DUE_PREFIX) ? DueStatus::tryFrom(substr($this->status, strlen(self::DUE_PREFIX))) : null;
        $valid = fn (string $date): bool => preg_match('/^\d{4}-\d{2}-\d{2}$/', $date) === 1;

        return Document::query()->visibleTo(auth()->user())
            ->whereIn('documents.company_id', app(CompanyContext::class)->companyIds())
            ->where('documents.type', $type)
            ->when($search !== '', fn (Builder $query) => $query->where(fn (Builder $query) => $query
                ->where('documents.number', 'like', '%'.$search.'%')
                ->orWhere('documents.reference', 'like', '%'.$search.'%')
                ->orWhere('documents.title', 'like', '%'.$search.'%')
                ->orWhereIn('documents.party_id', Party::query()->select('id')->where('name', 'like', '%'.$search.'%'))))
            ->when($status !== null, fn (Builder $query) => $query->where('documents.status', $status))
            ->when($dueStatus !== null && $type->isPayable(), fn (Builder $query) => $query->dueStatus($dueStatus))
            ->when($valid($this->from), fn (Builder $query) => $query->where('documents.issue_date', '>=', $this->from))
            ->when($valid($this->to), fn (Builder $query) => $query->where('documents.issue_date', '<=', $this->to))
            ->when(ctype_digit($this->party), fn (Builder $query) => $query->where('documents.party_id', (int) $this->party))
            ->when(ctype_digit($this->recurring), fn (Builder $query) => $query->where('documents.recurring_invoice_id', (int) $this->recurring));
    }
}
