<div class="page">
    <x-notices />
    <x-page-header :title="$documentType->pluralLabel()" :description="__('Drafts have no number until they are issued. Void documents stay listed but never count in totals.')">
        <x-slot:actions>
            @can('sales.create')
                @unless($showCompany)
                    <x-button icon="plus" :href="route('admin.sales.'.$documentType->slug().'.create')">{{ __('New :type', ['type' => mb_strtolower($documentType->label())]) }}</x-button>
                @endunless
            @endcan
        </x-slot:actions>
    </x-page-header>
    <div class="stats">
        <x-stat :label="__('Issued')" emoji="🧾" :value="$totals['count']" />
        <x-stat :label="__('Total')" emoji="💼" tone="info"><x-slot:value><x-money :value="$totals['total']" /></x-slot:value></x-stat>
        @if($totals['balance'] !== null)
            <x-stat :label="$documentType->isPurchase() ? __('Still to pay') : __('Still to receive')" emoji="⏳" tone="warning"><x-slot:value><x-money :value="$totals['balance']" /></x-slot:value></x-stat>
        @endif
    </div>
    @if($schedule)<x-alert tone="info">{{ __('Showing the invoices generated by the recurring schedule :name.', ['name' => $schedule]) }} <button type="button" class="text-link" wire:click="$set('recurring', '')">{{ __('Show all') }}</button></x-alert>@endif
    <x-card flush>
        <x-slot:toolbar>
            <x-toolbar :active="$active">
                <x-form.input name="search" :label="__('Search')" type="search" wire:model.live.debounce.300ms="search" maxlength="100" :placeholder="__('Number, party or reference.')" />
                <x-form.date-range :label="__('Date')" />
                <x-slot:filters>
                    <x-form.select name="status" :label="__('Status')" wire:model.live="status" :options="$statuses" />
                    <x-form.select name="party" :label="$documentType->isPurchase() ? __('Supplier') : __('Customer')" wire:model.live="party" :options="$parties" />
                </x-slot:filters>
                <x-slot:clear><x-button variant="ghost" icon="filter-x" wire:click="clearFilters">{{ __('Clear filters') }}</x-button></x-slot:clear>
            </x-toolbar>
        </x-slot:toolbar>
        @php($columns = 5 + ($showCompany ? 1 : 0) + ($documentType->isPayable() ? 1 : 0))
        <x-table :caption="$documentType->pluralLabel()">
            <x-slot:head>
                <th>{{ __('Number') }}</th>
                <th>{{ $documentType->isPurchase() ? __('Supplier') : __('Customer') }}</th>
                @if($showCompany)<th>{{ __('Company') }}</th>@endif
                <th class="num">{{ __('Total') }}</th>
                @if($documentType->isPayable())<th class="num">{{ __('Balance') }}</th>@endif
                <th>{{ __('Status') }}</th>
                <th class="actions-col"><span class="sr-only">{{ __('Actions') }}</span></th>
            </x-slot:head>
            @forelse($documents as $document)
                <tr wire:key="document-{{ $document->id }}" @class(['is-voided' => $document->isVoid()])>
                    <td class="nowrap">
                        <a class="text-link" href="{{ route('admin.sales.documents.show', $document) }}" wire:navigate>{{ $document->number ?? __('Draft') }}</a>
                        <p class="muted">{{ $document->issue_date->format('d M Y') }}</p>
                    </td>
                    <td>{{ $document->party?->name ?? '—' }}@if($document->title)<p class="muted">{{ $document->title }}</p>@endif @if($document->reference)<p class="muted">{{ __('Ref: :reference', ['reference' => $document->reference]) }}</p>@endif</td>
                    @if($showCompany)<td>{{ $document->company->name }}</td>@endif
                    <td class="num">@if($document->isVoid())<s><x-money :value="$document->total" /></s>@else<x-money :value="$document->total" />@endif</td>
                    @if($documentType->isPayable())
                        <td class="num">@if($document->balance() !== null)<x-money :value="max(0, $document->balance())" />@if($document->due_date && $document->balance() > 0)<p class="muted">{{ __('Due :date', ['date' => $document->due_date->format('d M Y')]) }}</p>@endif @else—@endif</td>
                    @endif
                    <td>
                        <div class="btn-group">
                            <x-badge :tone="$document->status->tone()">{{ $document->status->label() }}</x-badge>
                            @if($document->type->isPayable())<x-badge.due-status :status="$document->dueStatus()" />@endif
                            @if($document->isPosted())<x-badge tone="primary" :title="__('Posted to the books')">{{ __('Posted') }}</x-badge>@endif
                        </div>
                    </td>
                    <td><div class="row-actions"><x-button variant="ghost" size="sm" icon="eye" :href="route('admin.sales.documents.show', $document)" :label="__('Open :number', ['number' => $document->displayNumber()])" /></div></td>
                </tr>
            @empty
                <x-table.empty :colspan="$columns" emoji="🧾">{{ __('No :types found.', ['types' => mb_strtolower($documentType->pluralLabel())]) }}</x-table.empty>
            @endforelse
        </x-table>
        {{ $documents->links() }}
    </x-card>
</div>
